INSERT INTO "country" ("id", "value") VALUES (E'AF', E'Afghanistan');
INSERT INTO "country" ("id", "value") VALUES (E'AX', E'Åland Islands');
INSERT INTO "country" ("id", "value") VALUES (E'AL', E'Albania');
INSERT INTO "country" ("id", "value") VALUES (E'DZ', E'Algeria');
INSERT INTO "country" ("id", "value") VALUES (E'AS', E'American Samoa');
INSERT INTO "country" ("id", "value") VALUES (E'AD', E'Andorra');
INSERT INTO "country" ("id", "value") VALUES (E'AO', E'Angola');
INSERT INTO "country" ("id", "value") VALUES (E'AI', E'Anguilla');
INSERT INTO "country" ("id", "value") VALUES (E'AQ', E'Antarctica');
INSERT INTO "country" ("id", "value") VALUES (E'AG', E'Antigua & Barbuda');
INSERT INTO "country" ("id", "value") VALUES (E'AR', E'Argentina');
INSERT INTO "country" ("id", "value") VALUES (E'AM', E'Armenia');
INSERT INTO "country" ("id", "value") VALUES (E'AW', E'Aruba');
INSERT INTO "country" ("id", "value") VALUES (E'AU', E'Australia');
INSERT INTO "country" ("id", "value") VALUES (E'AT', E'Austria');
INSERT INTO "country" ("id", "value") VALUES (E'AZ', E'Azerbaijan');
INSERT INTO "country" ("id", "value") VALUES (E'BS', E'Bahamas');
INSERT INTO "country" ("id", "value") VALUES (E'BH', E'Bahrain');
INSERT INTO "country" ("id", "value") VALUES (E'BD', E'Bangladesh');
INSERT INTO "country" ("id", "value") VALUES (E'BB', E'Barbados');
INSERT INTO "country" ("id", "value") VALUES (E'BY', E'Belarus');
INSERT INTO "country" ("id", "value") VALUES (E'BE', E'Belgium');
INSERT INTO "country" ("id", "value") VALUES (E'BZ', E'Belize');
INSERT INTO "country" ("id", "value") VALUES (E'BJ', E'Benin');
INSERT INTO "country" ("id", "value") VALUES (E'BM', E'Bermuda');
INSERT INTO "country" ("id", "value") VALUES (E'BT', E'Bhutan');
INSERT INTO "country" ("id", "value") VALUES (E'BO', E'Bolivia');
INSERT INTO "country" ("id", "value") VALUES (E'BA', E'Bosnia & Herzegovina');
INSERT INTO "country" ("id", "value") VALUES (E'BW', E'Botswana');
INSERT INTO "country" ("id", "value") VALUES (E'BV', E'Bouvet Island');
INSERT INTO "country" ("id", "value") VALUES (E'BR', E'Brazil');
INSERT INTO "country" ("id", "value") VALUES (E'IO', E'British Indian Ocean Territory');
INSERT INTO "country" ("id", "value") VALUES (E'VG', E'British Virgin Islands');
INSERT INTO "country" ("id", "value") VALUES (E'BN', E'Brunei');
INSERT INTO "country" ("id", "value") VALUES (E'BG', E'Bulgaria');
INSERT INTO "country" ("id", "value") VALUES (E'BF', E'Burkina Faso');
INSERT INTO "country" ("id", "value") VALUES (E'BI', E'Burundi');
INSERT INTO "country" ("id", "value") VALUES (E'KH', E'Cambodia');
INSERT INTO "country" ("id", "value") VALUES (E'CM', E'Cameroon');
INSERT INTO "country" ("id", "value") VALUES (E'CA', E'Canada');
INSERT INTO "country" ("id", "value") VALUES (E'CV', E'Cape Verde');
INSERT INTO "country" ("id", "value") VALUES (E'BQ', E'Caribbean Netherlands');
INSERT INTO "country" ("id", "value") VALUES (E'KY', E'Cayman Islands');
INSERT INTO "country" ("id", "value") VALUES (E'CF', E'Central African Republic');
INSERT INTO "country" ("id", "value") VALUES (E'TD', E'Chad');
INSERT INTO "country" ("id", "value") VALUES (E'CL', E'Chile');
INSERT INTO "country" ("id", "value") VALUES (E'CN', E'China');
INSERT INTO "country" ("id", "value") VALUES (E'CX', E'Christmas Island');
INSERT INTO "country" ("id", "value") VALUES (E'CC', E'Cocos (Keeling) Islands');
INSERT INTO "country" ("id", "value") VALUES (E'CO', E'Colombia');
INSERT INTO "country" ("id", "value") VALUES (E'KM', E'Comoros');
INSERT INTO "country" ("id", "value") VALUES (E'CG', E'Congo - Brazzaville');
INSERT INTO "country" ("id", "value") VALUES (E'CD', E'Congo - Kinshasa');
INSERT INTO "country" ("id", "value") VALUES (E'CK', E'Cook Islands');
INSERT INTO "country" ("id", "value") VALUES (E'CR', E'Costa Rica');
INSERT INTO "country" ("id", "value") VALUES (E'CI', E'Côte d’Ivoire');
INSERT INTO "country" ("id", "value") VALUES (E'HR', E'Croatia');
INSERT INTO "country" ("id", "value") VALUES (E'CU', E'Cuba');
INSERT INTO "country" ("id", "value") VALUES (E'CW', E'Curaçao');
INSERT INTO "country" ("id", "value") VALUES (E'CY', E'Cyprus');
INSERT INTO "country" ("id", "value") VALUES (E'CZ', E'Czechia');
INSERT INTO "country" ("id", "value") VALUES (E'DK', E'Denmark');
INSERT INTO "country" ("id", "value") VALUES (E'DJ', E'Djibouti');
INSERT INTO "country" ("id", "value") VALUES (E'DM', E'Dominica');
INSERT INTO "country" ("id", "value") VALUES (E'DO', E'Dominican Republic');
INSERT INTO "country" ("id", "value") VALUES (E'EC', E'Ecuador');
INSERT INTO "country" ("id", "value") VALUES (E'EG', E'Egypt');
INSERT INTO "country" ("id", "value") VALUES (E'SV', E'El Salvador');
INSERT INTO "country" ("id", "value") VALUES (E'GQ', E'Equatorial Guinea');
INSERT INTO "country" ("id", "value") VALUES (E'ER', E'Eritrea');
INSERT INTO "country" ("id", "value") VALUES (E'EE', E'Estonia');
INSERT INTO "country" ("id", "value") VALUES (E'SZ', E'Eswatini');
INSERT INTO "country" ("id", "value") VALUES (E'ET', E'Ethiopia');
INSERT INTO "country" ("id", "value") VALUES (E'FK', E'Falkland Islands');
INSERT INTO "country" ("id", "value") VALUES (E'FO', E'Faroe Islands');
INSERT INTO "country" ("id", "value") VALUES (E'FJ', E'Fiji');
INSERT INTO "country" ("id", "value") VALUES (E'FI', E'Finland');
INSERT INTO "country" ("id", "value") VALUES (E'FR', E'France');
INSERT INTO "country" ("id", "value") VALUES (E'GF', E'French Guiana');
INSERT INTO "country" ("id", "value") VALUES (E'PF', E'French Polynesia');
INSERT INTO "country" ("id", "value") VALUES (E'TF', E'French Southern Territories');
INSERT INTO "country" ("id", "value") VALUES (E'GA', E'Gabon');
INSERT INTO "country" ("id", "value") VALUES (E'GM', E'Gambia');
INSERT INTO "country" ("id", "value") VALUES (E'GE', E'Georgia');
INSERT INTO "country" ("id", "value") VALUES (E'DE', E'Germany');
INSERT INTO "country" ("id", "value") VALUES (E'GH', E'Ghana');
INSERT INTO "country" ("id", "value") VALUES (E'GI', E'Gibraltar');
INSERT INTO "country" ("id", "value") VALUES (E'GR', E'Greece');
INSERT INTO "country" ("id", "value") VALUES (E'GL', E'Greenland');
INSERT INTO "country" ("id", "value") VALUES (E'GD', E'Grenada');
INSERT INTO "country" ("id", "value") VALUES (E'GP', E'Guadeloupe');
INSERT INTO "country" ("id", "value") VALUES (E'GU', E'Guam');
INSERT INTO "country" ("id", "value") VALUES (E'GT', E'Guatemala');
INSERT INTO "country" ("id", "value") VALUES (E'GG', E'Guernsey');
INSERT INTO "country" ("id", "value") VALUES (E'GN', E'Guinea');
INSERT INTO "country" ("id", "value") VALUES (E'GW', E'Guinea-Bissau');
INSERT INTO "country" ("id", "value") VALUES (E'GY', E'Guyana');
INSERT INTO "country" ("id", "value") VALUES (E'HT', E'Haiti');
INSERT INTO "country" ("id", "value") VALUES (E'HM', E'Heard & McDonald Islands');
INSERT INTO "country" ("id", "value") VALUES (E'HN', E'Honduras');
INSERT INTO "country" ("id", "value") VALUES (E'HK', E'Hong Kong SAR China');
INSERT INTO "country" ("id", "value") VALUES (E'HU', E'Hungary');
INSERT INTO "country" ("id", "value") VALUES (E'IS', E'Iceland');
INSERT INTO "country" ("id", "value") VALUES (E'IN', E'India');
INSERT INTO "country" ("id", "value") VALUES (E'ID', E'Indonesia');
INSERT INTO "country" ("id", "value") VALUES (E'IR', E'Iran');
INSERT INTO "country" ("id", "value") VALUES (E'IQ', E'Iraq');
INSERT INTO "country" ("id", "value") VALUES (E'IE', E'Ireland');
INSERT INTO "country" ("id", "value") VALUES (E'IM', E'Isle of Man');
INSERT INTO "country" ("id", "value") VALUES (E'IL', E'Israel');
INSERT INTO "country" ("id", "value") VALUES (E'IT', E'Italy');
INSERT INTO "country" ("id", "value") VALUES (E'JM', E'Jamaica');
INSERT INTO "country" ("id", "value") VALUES (E'JP', E'Japan');
INSERT INTO "country" ("id", "value") VALUES (E'JE', E'Jersey');
INSERT INTO "country" ("id", "value") VALUES (E'JO', E'Jordan');
INSERT INTO "country" ("id", "value") VALUES (E'KZ', E'Kazakhstan');
INSERT INTO "country" ("id", "value") VALUES (E'KE', E'Kenya');
INSERT INTO "country" ("id", "value") VALUES (E'KI', E'Kiribati');
INSERT INTO "country" ("id", "value") VALUES (E'KW', E'Kuwait');
INSERT INTO "country" ("id", "value") VALUES (E'KG', E'Kyrgyzstan');
INSERT INTO "country" ("id", "value") VALUES (E'LA', E'Laos');
INSERT INTO "country" ("id", "value") VALUES (E'LV', E'Latvia');
INSERT INTO "country" ("id", "value") VALUES (E'LB', E'Lebanon');
INSERT INTO "country" ("id", "value") VALUES (E'LS', E'Lesotho');
INSERT INTO "country" ("id", "value") VALUES (E'LR', E'Liberia');
INSERT INTO "country" ("id", "value") VALUES (E'LY', E'Libya');
INSERT INTO "country" ("id", "value") VALUES (E'LI', E'Liechtenstein');
INSERT INTO "country" ("id", "value") VALUES (E'LT', E'Lithuania');
INSERT INTO "country" ("id", "value") VALUES (E'LU', E'Luxembourg');
INSERT INTO "country" ("id", "value") VALUES (E'MO', E'Macao SAR China');
INSERT INTO "country" ("id", "value") VALUES (E'MG', E'Madagascar');
INSERT INTO "country" ("id", "value") VALUES (E'MW', E'Malawi');
INSERT INTO "country" ("id", "value") VALUES (E'MY', E'Malaysia');
INSERT INTO "country" ("id", "value") VALUES (E'MV', E'Maldives');
INSERT INTO "country" ("id", "value") VALUES (E'ML', E'Mali');
INSERT INTO "country" ("id", "value") VALUES (E'MT', E'Malta');
INSERT INTO "country" ("id", "value") VALUES (E'MH', E'Marshall Islands');
INSERT INTO "country" ("id", "value") VALUES (E'MQ', E'Martinique');
INSERT INTO "country" ("id", "value") VALUES (E'MR', E'Mauritania');
INSERT INTO "country" ("id", "value") VALUES (E'MU', E'Mauritius');
INSERT INTO "country" ("id", "value") VALUES (E'YT', E'Mayotte');
INSERT INTO "country" ("id", "value") VALUES (E'MX', E'Mexico');
INSERT INTO "country" ("id", "value") VALUES (E'FM', E'Micronesia');
INSERT INTO "country" ("id", "value") VALUES (E'MD', E'Moldova');
INSERT INTO "country" ("id", "value") VALUES (E'MC', E'Monaco');
INSERT INTO "country" ("id", "value") VALUES (E'MN', E'Mongolia');
INSERT INTO "country" ("id", "value") VALUES (E'ME', E'Montenegro');
INSERT INTO "country" ("id", "value") VALUES (E'MS', E'Montserrat');
INSERT INTO "country" ("id", "value") VALUES (E'MA', E'Morocco');
INSERT INTO "country" ("id", "value") VALUES (E'MZ', E'Mozambique');
INSERT INTO "country" ("id", "value") VALUES (E'MM', E'Myanmar (Burma)');
INSERT INTO "country" ("id", "value") VALUES (E'NA', E'Namibia');
INSERT INTO "country" ("id", "value") VALUES (E'NR', E'Nauru');
INSERT INTO "country" ("id", "value") VALUES (E'NP', E'Nepal');
INSERT INTO "country" ("id", "value") VALUES (E'NL', E'Netherlands');
INSERT INTO "country" ("id", "value") VALUES (E'NC', E'New Caledonia');
INSERT INTO "country" ("id", "value") VALUES (E'NZ', E'New Zealand');
INSERT INTO "country" ("id", "value") VALUES (E'NI', E'Nicaragua');
INSERT INTO "country" ("id", "value") VALUES (E'NE', E'Niger');
INSERT INTO "country" ("id", "value") VALUES (E'NG', E'Nigeria');
INSERT INTO "country" ("id", "value") VALUES (E'NU', E'Niue');
INSERT INTO "country" ("id", "value") VALUES (E'NF', E'Norfolk Island');
INSERT INTO "country" ("id", "value") VALUES (E'KP', E'North Korea');
INSERT INTO "country" ("id", "value") VALUES (E'MK', E'North Macedonia');
INSERT INTO "country" ("id", "value") VALUES (E'MP', E'Northern Mariana Islands');
INSERT INTO "country" ("id", "value") VALUES (E'NO', E'Norway');
INSERT INTO "country" ("id", "value") VALUES (E'OM', E'Oman');
INSERT INTO "country" ("id", "value") VALUES (E'PK', E'Pakistan');
INSERT INTO "country" ("id", "value") VALUES (E'PW', E'Palau');
INSERT INTO "country" ("id", "value") VALUES (E'PS', E'Palestinian Territories');
INSERT INTO "country" ("id", "value") VALUES (E'PA', E'Panama');
INSERT INTO "country" ("id", "value") VALUES (E'PG', E'Papua New Guinea');
INSERT INTO "country" ("id", "value") VALUES (E'PY', E'Paraguay');
INSERT INTO "country" ("id", "value") VALUES (E'PE', E'Peru');
INSERT INTO "country" ("id", "value") VALUES (E'PH', E'Philippines');
INSERT INTO "country" ("id", "value") VALUES (E'PN', E'Pitcairn Islands');
INSERT INTO "country" ("id", "value") VALUES (E'PL', E'Poland');
INSERT INTO "country" ("id", "value") VALUES (E'PT', E'Portugal');
INSERT INTO "country" ("id", "value") VALUES (E'PR', E'Puerto Rico');
INSERT INTO "country" ("id", "value") VALUES (E'QA', E'Qatar');
INSERT INTO "country" ("id", "value") VALUES (E'RE', E'Réunion');
INSERT INTO "country" ("id", "value") VALUES (E'RO', E'Romania');
INSERT INTO "country" ("id", "value") VALUES (E'RU', E'Russia');
INSERT INTO "country" ("id", "value") VALUES (E'RW', E'Rwanda');
INSERT INTO "country" ("id", "value") VALUES (E'WS', E'Samoa');
INSERT INTO "country" ("id", "value") VALUES (E'SM', E'San Marino');
INSERT INTO "country" ("id", "value") VALUES (E'ST', E'São Tomé & Príncipe');
INSERT INTO "country" ("id", "value") VALUES (E'SA', E'Saudi Arabia');
INSERT INTO "country" ("id", "value") VALUES (E'SN', E'Senegal');
INSERT INTO "country" ("id", "value") VALUES (E'RS', E'Serbia');
INSERT INTO "country" ("id", "value") VALUES (E'SC', E'Seychelles');
INSERT INTO "country" ("id", "value") VALUES (E'SL', E'Sierra Leone');
INSERT INTO "country" ("id", "value") VALUES (E'SG', E'Singapore');
INSERT INTO "country" ("id", "value") VALUES (E'SX', E'Sint Maarten');
INSERT INTO "country" ("id", "value") VALUES (E'SK', E'Slovakia');
INSERT INTO "country" ("id", "value") VALUES (E'SI', E'Slovenia');
INSERT INTO "country" ("id", "value") VALUES (E'SB', E'Solomon Islands');
INSERT INTO "country" ("id", "value") VALUES (E'SO', E'Somalia');
INSERT INTO "country" ("id", "value") VALUES (E'ZA', E'South Africa');
INSERT INTO "country" ("id", "value") VALUES (E'GS', E'South Georgia & South Sandwich Islands');
INSERT INTO "country" ("id", "value") VALUES (E'KR', E'South Korea');
INSERT INTO "country" ("id", "value") VALUES (E'SS', E'South Sudan');
INSERT INTO "country" ("id", "value") VALUES (E'ES', E'Spain');
INSERT INTO "country" ("id", "value") VALUES (E'LK', E'Sri Lanka');
INSERT INTO "country" ("id", "value") VALUES (E'BL', E'St. Barthélemy');
INSERT INTO "country" ("id", "value") VALUES (E'SH', E'St. Helena');
INSERT INTO "country" ("id", "value") VALUES (E'KN', E'St. Kitts & Nevis');
INSERT INTO "country" ("id", "value") VALUES (E'LC', E'St. Lucia');
INSERT INTO "country" ("id", "value") VALUES (E'MF', E'St. Martin');
INSERT INTO "country" ("id", "value") VALUES (E'PM', E'St. Pierre & Miquelon');
INSERT INTO "country" ("id", "value") VALUES (E'VC', E'St. Vincent & Grenadines');
INSERT INTO "country" ("id", "value") VALUES (E'SD', E'Sudan');
INSERT INTO "country" ("id", "value") VALUES (E'SR', E'Suriname');
INSERT INTO "country" ("id", "value") VALUES (E'SJ', E'Svalbard & Jan Mayen');
INSERT INTO "country" ("id", "value") VALUES (E'SE', E'Sweden');
INSERT INTO "country" ("id", "value") VALUES (E'CH', E'Switzerland');
INSERT INTO "country" ("id", "value") VALUES (E'SY', E'Syria');
INSERT INTO "country" ("id", "value") VALUES (E'TW', E'Taiwan');
INSERT INTO "country" ("id", "value") VALUES (E'TJ', E'Tajikistan');
INSERT INTO "country" ("id", "value") VALUES (E'TZ', E'Tanzania');
INSERT INTO "country" ("id", "value") VALUES (E'TH', E'Thailand');
INSERT INTO "country" ("id", "value") VALUES (E'TL', E'Timor-Leste');
INSERT INTO "country" ("id", "value") VALUES (E'TG', E'Togo');
INSERT INTO "country" ("id", "value") VALUES (E'TK', E'Tokelau');
INSERT INTO "country" ("id", "value") VALUES (E'TO', E'Tonga');
INSERT INTO "country" ("id", "value") VALUES (E'TT', E'Trinidad & Tobago');
INSERT INTO "country" ("id", "value") VALUES (E'TN', E'Tunisia');
INSERT INTO "country" ("id", "value") VALUES (E'TR', E'Turkey');
INSERT INTO "country" ("id", "value") VALUES (E'TM', E'Turkmenistan');
INSERT INTO "country" ("id", "value") VALUES (E'TC', E'Turks & Caicos Islands');
INSERT INTO "country" ("id", "value") VALUES (E'TV', E'Tuvalu');
INSERT INTO "country" ("id", "value") VALUES (E'UM', E'U.S. Outlying Islands');
INSERT INTO "country" ("id", "value") VALUES (E'VI', E'U.S. Virgin Islands');
INSERT INTO "country" ("id", "value") VALUES (E'UG', E'Uganda');
INSERT INTO "country" ("id", "value") VALUES (E'UA', E'Ukraine');
INSERT INTO "country" ("id", "value") VALUES (E'AE', E'United Arab Emirates');
INSERT INTO "country" ("id", "value") VALUES (E'GB', E'United Kingdom');
INSERT INTO "country" ("id", "value") VALUES (E'US', E'United States');
INSERT INTO "country" ("id", "value") VALUES (E'UY', E'Uruguay');
INSERT INTO "country" ("id", "value") VALUES (E'UZ', E'Uzbekistan');
INSERT INTO "country" ("id", "value") VALUES (E'VU', E'Vanuatu');
INSERT INTO "country" ("id", "value") VALUES (E'VA', E'Vatican City');
INSERT INTO "country" ("id", "value") VALUES (E'VE', E'Venezuela');
INSERT INTO "country" ("id", "value") VALUES (E'VN', E'Vietnam');
INSERT INTO "country" ("id", "value") VALUES (E'WF', E'Wallis & Futuna');
INSERT INTO "country" ("id", "value") VALUES (E'EH', E'Western Sahara');
INSERT INTO "country" ("id", "value") VALUES (E'YE', E'Yemen');
INSERT INTO "country" ("id", "value") VALUES (E'ZM', E'Zambia');
INSERT INTO "country" ("id", "value") VALUES (E'ZW', E'Zimbabwe');